---
defaults: &defaults
  host: 'localhost:3000'
  mailer_sender: tracker@bugs.cosmicvent.com

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  host: bugs.cosmicvent.com
